### ISSUE TITLE
Add framewok into config

### ISSUE THREAD

**Issue by black23** [PTFS-Europe/koha-ill-freeform#10]

**Comment by black23** [comment]
We really need to set framework in configuration.

# We hardcode a framework name of 'FA', which will need to exist

    # All this stuff should be configurable

**Comment by AndrewIsh** [comment]
Agreed. Framework should definitely be in the ILL configuration.

**Comment by AndrewIsh** [comment]
This has now been closed with https://github.com/PTFS-Europe/koha-ill-freeform/commit/0e6b9be8007de8b75b30a41eee1ad2e6bc85072d which allows a `<framework>` element to be defined in the main `<interlibrary_loans>` config, e.g.
```
<interlibrary_loans>
    <framework>AB</framework>
...
</interlibrary_loans>
```
