### ISSUE TITLE
Wrong coding if diacritic is used in Author or title

### ISSUE THREAD

**Issue by ViliamPolonec** [PTFS-Europe/koha-ill-freeform#15]
I tried this Illbackends and I have som problems with coding. If I fill author or title with diacritics, letters like á, é, š, ... they are wrong copied to marc record. In Intranet Details for all requests is everything ok, but when I click on the bib record then diacritics is wrong or missing. If I write author wich begin with Á then in marc record is field 100$a empty

**Comment by AndrewIsh** [comment]
This has now been fixed with https://github.com/PTFS-Europe/koha-ill-freeform/commit/fd08b025b27e7a9dcbdaab5b406498c046381aae

Closing.

**Comment by ViliamPolonec** [comment]
thank you very much
great work
