### ISSUE TITLE
Cannot list ILL requests?

### ISSUE THREAD

**Issue by lizrea** [PTFS-Europe/koha-ill-freeform#16]
I'm having a problem where we can't seem to get the list of ILL requests to come out, the API comes back with this: 

{"errors":[{"message":"Not in enum list: patron, library, capabilities, metadata, requested_partners.","path":"\/embed\/4"},{"message":"Not in enum list: patron, library, capabilities, metadata, requested_partners.","path":"\/embed\/5"}],"status":400}

Have we installed this wrong somehow? Has Koha changed underneath us?

**Comment by AndrewIsh** [comment]
Hi @lizrea This is due to the one of the Koha API dependencies (I forget which) becoming stricter in its validation and, the ILL route then failing its validation. The fix is here: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=25944 I'll close this bug.
