### ISSUE TITLE
Add client side validation for required fields like destination library

### ISSUE THREAD

**Issue by kfischer** [PTFS-Europe/koha-ill-freeform#5]
Right now if you forget to enter the 'destination library' when creating a new ill request from the staff side, you will receive an error on top after submitting: 

We encountered an error:   (missing_branch)

This is not very user friendly. I think it would be nicer if the form validated input client side before submitting as we do on other forms (look at any in administration module for examples)

**Comment by AndrewIsh** [comment]
This was done as part of https://github.com/PTFS-Europe/koha-ill-freeform/commit/5d86ceca5c549ae400166f90e9fb2f0da414d92f It is now not possible to submit a request without a branch first having been selected
