### ISSUE TITLE
add pages to defined fields for article

### ISSUE THREAD

**Issue by mkstephens** [PTFS-Europe/koha-ill-freeform#7]
The current /shared-includes/forms/article.inc does not include a field for pages. In the previous iteration of this form, the field was defined as "article_pages." The chapter.inc file uses "pages" which would also work for article.

Thank you!

**Comment by mkstephens** [comment]
I would also like to add that openURL seems to require a field to be present in order to pass data to it. Without a field for pages, this data is getting lost when it is passed from an openURL query string. 

An openURL query string does not seem to have the ability to add custom fields if the field it is sending information to is not present. At least, not the openURL query strings that I am currently able to write and test with the freeform backend. Therefore, with the changes made to the form since the 18.05 release, I'm finding it very important to correctly match on type so that the correct fields are available for the rest of the data in the openURL. I can no longer fall back on "other" because there aren't any fields defined in other.inc. If there's another way to write an openURL query string so that it can create custom fields if the field called for does not exist, I would very much like to know how to do that.

**Comment by mrenvoize** [comment]
This plays into the work you've been doing on forms right @AndrewIsh ?

**Comment by mkstephens** [comment]
Thank you for adding pages to article.inc. I've attempted to add some general, basic fields to other.inc and created a pull request.

**Comment by AndrewIsh** [comment]
Pull request was merged some time ago, closing.
